### ISSUE TITLE
[HIGH] F2b: As Admin, I want to burn any token in my posession

### ISSUE THREAD

**Issue by zahhar** [epam/mintgate#10]
Admin (MintGate) may claim all token copies of any GateID and then burn any of them (if token is already claimed (has an Owner), then Admin cannot claim it, but needs to obtain through a Marketplace). 
Admin CAN burn only tokens that he owns.
Admin CAN NOT burn any tokens that he does not own.

Implementation details:
If Token.Owner == Contract.Account? - can we determine it from the environment?

**Comment by acuarica** [comment]
Merged into #112.
