### ISSUE TITLE
F9: As an Owner, I want to transfer my token to any NEAR User

### ISSUE THREAD

**Issue by zahhar** [epam/mintgate#18]
Only Owner can transfer a Token that he owns.
Any other token cannot be transferred. 

NB! Frontend must ensure that NEAR Account exists, as it is not possible to do in BE without cross-contract calls.

**Comment by zahhar** [comment]
@sxurik - is it tested?

**Comment by sxurik** [comment]
> @sxurik - is it tested?

Yup, happy path and errors: 
- if sender and receiver are one person;
- if sender doesn't own the token.

**Comment by zahhar** [comment]
@sxurik - then closing, thank you!
