### ISSUE TITLE
M1 demo feedback: more realistic test data

### ISSUE THREAD

**Issue by zahhar** [epam/mintgate#49]
Once Mintgate provides more realistic test data - we have to update test cases.

**Comment by zahhar** [comment]
Let's discuss what Metadata attributes are mandatory for Collectible.

## Standard struct

```
Metadata {
                title: **mandatory**
                description: **tbd**
                media: **tbd**
                media_hash: **tbd**
                copies: **mandatory, minimum 1**
                issued_at: **automatic**
                expires_at: **not in use**
                starts_at: **not in use**
                updated_at: **automatic**
                extra: **tbd**
                reference: **tbd**
                reference_hash: **tbd**
            },
```

# Discussion

- **Title**: strictly mandatory, probably we all agree here that there cannot be any Collectible produced without it? What is MAX_LENGTH?
- **Description**: looks more like optional field that can be omitted, but current Mintgate.app GUI requires it to be filled. So we can either implement same check within the contract if you are sure Description remains mandatory, or we can leave it optional on the contract level, and you can enforce it to be filled in the GUI. Any MAX_LENGTH limit co be considered here?
- **Media**: this is typically something visual that depicts the token: image or video. It is not intended for ZIP/PDF/whatsoever downloadable file. 
- **Media_Hash**: strongly recommended if you are NOT hosting Media file in IPFS or any other distributed storage and want to provide tamper-proof solution. 
- **Extra**: we do not foresee a need to store anything here. Unless there is any data in Mintgate that MUST BE stored on-chain?
- **copies**: any upper limit foreseen in Mintgate? Do you use the BigInt? Or 2^16 / 2^32 would be enough?
- **reference:** this is a good place where to store extrenal URL (unlockable URL) or some downloadable (ZIP, PDF, etc). Again if you want to go ultimate with traditional HTTPS storage (S3, whatsowever), reference_hash is recommended.

**Comment by Jshanks21** [comment]
**Title**: Agreed. MAX_LENGTH = 16 characters
**Description**: Leave it optional on the contract level and we'll enforce it in the GUI. It's possible we may not make this field mandatory in the GUI in the future. No MAX_LENGTH limit here.
**Media**: Understood. This will be required and should just be any link.
**Media_Hash**: We are not hosting on IPFS, but we would like this to be optional to maintain our flexibility to change our image compression or metadata after token is created if needed or improves performance.
**Extra**: No data seems relevant to add for this field at this time.
**copies**: Just to clarify, this is for copies of any one specific NFT, not all NFTs in the contract, correct? If so, 2^16 would be enough.
**reference**: Sounds great. We may move to IPFS at some point, but for the foreseeable future we will continue to use traditional storage. 
**reference_hash**: Even though we are not using IPFS currently, we would like this to be optional to maintain our flexibility to change our image compression or metadata after token is created if needed or improves performance.

Reasoning for optional media and reference hashes:

It would be better for us to use hashes later once we're 100% locked into image compression and metadata schema, however, we are not there yet.

**Comment by zahhar** [comment]
@Jshanks21 - all understood and will be implemented. One little detail if I may: 16 characters for title sounds like a strict limit, also seems current GUI does not have it. Won't you run into issues accomodating long titles that might include international charactes and emojis? I opened one random marketplace and picket just a few names from home page:

- No.0 超神聖杯ピピリオン/Super Holy Grail Pipirion -- 40 symbols
- Turbulence Particle Edition -- 27 symbols
- Ethereum Crypto Key for Crypto Art (2/3) - 41 symbols

I'd probably woulg go more flex way and limit title with smth between 64..256 characters, otherwise users has to be very creative minds to invent descriptive names fitting into 16 char limit :)

**Comment by zahhar** [comment]
Agreed as follows: 

- Title length to be 140 chars to match DB field. 
- Media and Reference will store the absolute URLs (starting with https:// or http:// or ipfs:// - whatever is given, no validation)
- _hash and description are optional 
- Extra won't be used
- Copies: limited to U16

**Comment by zahhar** [comment]
https://www.mintgate.app/api/tokenid/6
