### ISSUE TITLE
F11: As a User, I want to see all items listed on Mintgate marketplace

### ISSUE THREAD

**Issue by zahhar** [epam/mintgate#58]
1. View method that returns all TokenIds listed on the Marketplace
2. View method that returns all TokenIds listed on the Marketplace by GateId
3. View method that returns all TokenIds listed on the Marketplace by OwnerAccountId
4. View method that returns all TokenIds listed on the Marketplace by CreatorAccountId

_NB! Pagination for this method is Out of Scope of Milestone 2. It might be implemented in Milestone 3 after finishing discussion in the NEP-181 (https://github.com/near/NEPs/discussions/181) about ordered list of Tokens. As of know list of Tokens is unordered, that makes Pagination not that easy._

**Comment by Jshanks21** [comment]
1. Sounds great

The following are fine as part of M3 after discussions on NET-181 are finished.

2. Yes, GateId is our primary key, so being able to use it as a lookup will be useful in nearly all cases.
3. Not required, but preferred to have for convenience.
4. Yes, required to easily display creator collections from specific creator for sale.

**Comment by zahhar** [comment]
We will implement all 1-4 points in Milestone 2. 
Pagination is already captured as an extension to Milestone 3: #47
