### ISSUE TITLE
F4: As a NEAR User, I want to mint a Token of selected Collectible

### ISSUE THREAD

**Issue by acuarica** [epam/mintgate#6]
1. No one can mint more than TokenMetadata.Supply from the contract.
2. Claiming token initially is free, it does not require a Marketplace, and it does not generate any revenue, fees or royalties.
3. The total supply of tokens should not be minted immediately or all at once. 
4. The Artist can act as a Claimer and mint none, some, or all tokens up to the max supply at their discretion. 
5. The Admin (MintGate) will mint on behalf of Claimers. In this event, the Admin (MintGate) will call the mint function and pass the Claimer’s NEAR account that the token should be minted to. 
6. Claimer becomes an Owner of the NFT copy.

**Comment by zahhar** [comment]
@Jshanks21: is it correct that arbitrary NEAT AccountID cannot mint a token by calling contract directly? So we have to implement a protection that minting is exclusively allowed only to MintGate Admin? 

If this is true, then is also assumption correct that MintgGate Admin will act under the same account (or parent account) that deployed a contract? E.g. if contract is deployed to nft.mintgate.near, then nft.mintgate.near and mintgate.near will be authorized as Admins who can mint?

**Comment by Jshanks21** [comment]
> is it correct that arbitrary NEAT AccountID cannot mint a token by calling contract directly? So we have to implement a protection that minting is exclusively allowed only to MintGate Admin?

Correct

> MintgGate Admin will act under the same account (or parent account) that deployed a contract? E.g. if contract is deployed to nft.mintgate.near, then nft.mintgate.near and mintgate.near will be authorized as Admins who can mint?

Correct

**Comment by zahhar** [comment]
@Jshanks21 - may I ask why do you ask for: "_The Admin (MintGate) will mint on behalf of Claimers. In this event, the Admin (MintGate) will call the mint function and pass the Claimer’s NEAR account that the token should be minted to_."

Our current assumption is that Claimer User must have NEAR Account ID to claim the token and become an Owner for it, to be able to trade or gift it further. So it seems logical for us that Claimer User mints the token and pays for gas consumed.

What is the benefit of having AdminAccountID to be the only one who can claim tokens initially?

**Comment by zahhar** [comment]
Closing, tested & demonstrated to client. Leftovers created as new item for M2. #51
