### ISSUE TITLE
[HIGH] F2a: As a Creator, I can burn tokens I own that belong to Collectibles created by me

### ISSUE THREAD

**Issue by zahhar** [epam/mintgate#9]
Artist may claim all token copies of his own GateID(s) and burn any of them. 
Artist CAN NOT burn any tokens of GateIDs that he did not create. 
Artist CAN NOT burn any tokens of his GateID that he does not own.

_Implementation details_:
Check of Token.Owner == Collectible.Creator and only then allow to burn. Or there are other options?

**Comment by acuarica** [comment]
Merged into #112.
